# Local development compose file
services:
  nextjs:
    container_name: next-dev
    build:
      context: ./app
      target: dev
    env_file:
      # Add your non-secret environment variables to this file:
      - ./app/.env.development
      # If you have secrets, add them to this file and uncomment this line:
      # - ./app/.env.local
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
    restart: always
    ports:
      - 3000:3000

  storybook:
    container_name: storybook
    build:
      context: ./app
      target: dev
    command: npm run storybook
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
      - ./app/.storybook:/app/.storybook
      - ./app/stories:/app/stories
    restart: always
    ports:
      - 6006:6006
