# Production compose file
services:
  nextjs:
    build:
      context: ./app
      dockerfile: Dockerfile
      # Add your environment variables here
      # args:
      #   ENV_VARIABLE: ${ENV_VARIABLE}
      #   NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000
