name: Feature request
description: Suggest an idea for this project
labels: ["triage", "feature"]
projects: ["navapbc/4"]
body:
  - type: textarea
    attributes:
      label: Describe the problem and the solution you'd like
      description: A clear and concise description of what the problem is and what you want to happen.
      value: |
        ## Is your feature request related to a problem? Please describe.
        <!-- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] -->

        ## Describe the solution you'd like
        <!-- A clear and concise description of what you want to happen. -->

        ## Describe alternatives you've considered
        <!-- A clear and concise description of any alternative solutions or features you've considered. -->
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: dropdown
    attributes:
      label: Priority
      description: How impactful would this be for your project?
      multiple: false
      options:
        - "My project needs this now"
        - "I anticipate needing this soon"
        - "Nice to have"
        - "Just want to discuss"
