name: React CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - app/**
      - .github/workflows/ci-app.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./app

jobs:
  test:
    name: Tests and Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache-dependency-path: ./app/package-lock.json # or yarn.lock
          cache: npm # or yarn
      - run: npm ci
      - run: npm run format-check
      - run: npm run test

  # Confirms the app still builds successfully
  check-app-builds:
    name: Lint, Type check, and Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache-dependency-path: ./app/package-lock.json # or yarn.lock
          cache: npm # or yarn

      - run: npm ci

      # Next.js's build step runs lint and type checks too
      - name: Lint, Type check, and Build
        run: npm run build

  # Confirms Storybook still builds successfully
  check-storybook-builds:
    name: Storybook builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache-dependency-path: ./app/package-lock.json # or yarn.lock
          cache: npm # or yarn
      - run: npm ci
      - run: npm run storybook-build
