name: React CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - app/**
      - .github/workflows/ci-app.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./app

jobs:
  test:
    name: Test, Lint, Type check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache-dependency-path: ./app/package-lock.json # or yarn.lock
          cache: npm # or yarn
      - run: npm ci
      - run: npm run test
      - run: npm run lint
      - run: npm run ts:check
      - run: npm run format-check

  # Confirms the app still builds successfully
  check-app-builds:
    name: Build check - App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache-dependency-path: ./app/package-lock.json # or yarn.lock
          cache: npm # or yarn

      # https://nextjs.org/docs/advanced-features/ci-build-caching
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/app/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - run: npm ci
      - run: npm run build -- --no-lint

  # Confirms Storybook still builds successfully
  check-storybook-builds:
    name: Build check - Storybook
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache-dependency-path: ./app/package-lock.json # or yarn.lock
          cache: npm # or yarn
      - run: npm ci
      - run: npm run storybook-build
